name: Init Dashboard Data Repo
description: Check out repo and install dependencies

runs:
  using: composite
  steps:
    - name: Checkout Testing Tools Team Dashboard Data repo
      uses: actions/checkout@v2
      with:
        repository: department-of-veterans-affairs/testing-tools-team-dashboard-data
        token: ${{ env.VA_VSP_BOT_GITHUB_TOKEN }}
        path: testing-tools-team-dashboard-data

    - name: Get Node version
      id: get-node-version
      shell: bash
      run: echo ::set-output name=NODE_VERSION::$(cat .nvmrc)
      working-directory: testing-tools-team-dashboard-data

    - name: Setup Node
      uses: actions/setup-node@v2
      with:
        node-version: ${{ steps.get-node-version.outputs.NODE_VERSION }}

    - name: Install dependencies
      uses: ./.github/workflows/install
      with:
        key: ${{ hashFiles('yarn.lock') }}
        yarn_cache_folder: .cache/yarn
        path: |
          .cache/yarn
          node_modules